CREATE TABLE `zhihuuserinfo` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `userToken` varchar(255) DEFAULT NULL,
  `username` varchar(255) DEFAULT NULL,
  `gender` int(3) DEFAULT NULL,
  `business` varchar(255) DEFAULT NULL,
  `company` varchar(255) DEFAULT NULL,
  `position` varchar(255) DEFAULT NULL,
  `education` varchar(255) DEFAULT NULL,
  `location` varchar(255) DEFAULT NULL,
  `headline` varchar(255) DEFAULT NULL,
  `major` varchar(255) DEFAULT NULL,
  `answersNum` int(11) DEFAULT NULL,
  `starsNum` int(11) DEFAULT NULL,
  `thxNum` int(11) DEFAULT NULL,
  `portrait` varchar(11) DEFAULT NULL,
  `followingNum` int(11) DEFAULT NULL,
  `followersNum` int(11) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
